/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mypack;

import java.awt.Color;
import java.awt.FileDialog;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JColorChooser;

/**
 *
 * @author administrator
 */
public class DemoNotePad extends javax.swing.JFrame {

 /**
  * Creates new form DemoNotePad
  */
 public DemoNotePad() {
  initComponents();
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jScrollPane1 = new javax.swing.JScrollPane();
  jTextArea1 = new javax.swing.JTextArea();
  jMenuBar1 = new javax.swing.JMenuBar();
  jMenu1 = new javax.swing.JMenu();
  jMenuItem1 = new javax.swing.JMenuItem();
  jMenuItem2 = new javax.swing.JMenuItem();
  jMenuItem3 = new javax.swing.JMenuItem();
  jMenuItem4 = new javax.swing.JMenuItem();
  jMenu2 = new javax.swing.JMenu();
  jMenuItem5 = new javax.swing.JMenuItem();
  jMenuItem6 = new javax.swing.JMenuItem();
  jMenuItem7 = new javax.swing.JMenuItem();
  jMenuItem8 = new javax.swing.JMenuItem();
  jMenu3 = new javax.swing.JMenu();
  jMenuItem9 = new javax.swing.JMenuItem();
  jMenuItem10 = new javax.swing.JMenuItem();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

  jTextArea1.setColumns(20);
  jTextArea1.setRows(5);
  jScrollPane1.setViewportView(jTextArea1);

  jMenu1.setText("File");

  jMenuItem1.setText("New");
  jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem1ActionPerformed(evt);
   }
  });
  jMenu1.add(jMenuItem1);

  jMenuItem2.setText("Open");
  jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem2ActionPerformed(evt);
   }
  });
  jMenu1.add(jMenuItem2);

  jMenuItem3.setText("Save");
  jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem3ActionPerformed(evt);
   }
  });
  jMenu1.add(jMenuItem3);

  jMenuItem4.setText("Exit");
  jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem4ActionPerformed(evt);
   }
  });
  jMenu1.add(jMenuItem4);

  jMenuBar1.add(jMenu1);

  jMenu2.setText("Edit");

  jMenuItem5.setText("Select All");
  jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem5ActionPerformed(evt);
   }
  });
  jMenu2.add(jMenuItem5);

  jMenuItem6.setText("Cut");
  jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem6ActionPerformed(evt);
   }
  });
  jMenu2.add(jMenuItem6);

  jMenuItem7.setText("Copy");
  jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem7ActionPerformed(evt);
   }
  });
  jMenu2.add(jMenuItem7);

  jMenuItem8.setText("Paste");
  jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem8ActionPerformed(evt);
   }
  });
  jMenu2.add(jMenuItem8);

  jMenuBar1.add(jMenu2);

  jMenu3.setText("Format");

  jMenuItem9.setText("Foreground");
  jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem9ActionPerformed(evt);
   }
  });
  jMenu3.add(jMenuItem9);

  jMenuItem10.setText("Background");
  jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem10ActionPerformed(evt);
   }
  });
  jMenu3.add(jMenuItem10);

  jMenuBar1.add(jMenu3);

  setJMenuBar(jMenuBar1);

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
   jTextArea1.setText("");
 }//GEN-LAST:event_jMenuItem1ActionPerformed

 private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    FileDialog fd = new FileDialog(this,"Open File", FileDialog.LOAD);
    fd.show();
    
    String filePath = fd.getDirectory()+fd.getFile();
    try
    {
       File f = new File(filePath);
       FileReader fr = new FileReader(f);
       String data = "";
       while(true)
       {
         int x = fr.read();
         if(x == -1)
            break; 
          data = data +(char)x;
       }
       jTextArea1.setText(data);
    }
    catch(Exception ex)
    {
       System.out.println("Exception is : "+ex.toString());
    }
 }//GEN-LAST:event_jMenuItem2ActionPerformed

 private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
     FileDialog fd = new FileDialog(this,"Save File",FileDialog.SAVE);
     fd.show();
     String filePath = fd.getDirectory()+fd.getFile();
     try
     {
        File f = new File(filePath);
        FileWriter fw = new FileWriter(f);
        String data = jTextArea1.getText();
        fw.write(data);
        fw.close();
      }
      catch(Exception e)
      {
      
      }
 }//GEN-LAST:event_jMenuItem3ActionPerformed

 private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
   System.exit(0);
 }//GEN-LAST:event_jMenuItem4ActionPerformed

 private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
   jTextArea1.selectAll();
 }//GEN-LAST:event_jMenuItem5ActionPerformed

 private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
 
   jTextArea1.cut();
   
 }//GEN-LAST:event_jMenuItem6ActionPerformed

 private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
   jTextArea1.copy();
 }//GEN-LAST:event_jMenuItem7ActionPerformed

 private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
   jTextArea1.paste();
 }//GEN-LAST:event_jMenuItem8ActionPerformed

 private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
      Color c =  JColorChooser.showDialog(this, "Select Color", Color.yellow);
      jTextArea1.setForeground(c);
 }//GEN-LAST:event_jMenuItem9ActionPerformed

 private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
Color c =  JColorChooser.showDialog(this, "Select Color", Color.yellow);
      jTextArea1.setBackground(c);
 }//GEN-LAST:event_jMenuItem10ActionPerformed

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Nimbus look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(DemoNotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) {
   java.util.logging.Logger.getLogger(DemoNotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex) {
   java.util.logging.Logger.getLogger(DemoNotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
   java.util.logging.Logger.getLogger(DemoNotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
  //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    new DemoNotePad().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JMenu jMenu1;
 private javax.swing.JMenu jMenu2;
 private javax.swing.JMenu jMenu3;
 private javax.swing.JMenuBar jMenuBar1;
 private javax.swing.JMenuItem jMenuItem1;
 private javax.swing.JMenuItem jMenuItem10;
 private javax.swing.JMenuItem jMenuItem2;
 private javax.swing.JMenuItem jMenuItem3;
 private javax.swing.JMenuItem jMenuItem4;
 private javax.swing.JMenuItem jMenuItem5;
 private javax.swing.JMenuItem jMenuItem6;
 private javax.swing.JMenuItem jMenuItem7;
 private javax.swing.JMenuItem jMenuItem8;
 private javax.swing.JMenuItem jMenuItem9;
 private javax.swing.JScrollPane jScrollPane1;
 private javax.swing.JTextArea jTextArea1;
 // End of variables declaration//GEN-END:variables
}
